"""Shape and capability -> strategy selection.

The problem statement invites this directly: "participants can choose different
implementations for different shapes by adding shape checks in the
implementation of layers". This module is that choice, made from measurements
rather than from intuition.

The table it reads is generated by `analysis/load.py` from `results.csv`, so a
dispatch decision is traceable to the rows that justify it. But the submission
must never *depend* on a generated artefact — a judge cloning the repo and
running it with no `results/` directory has to get a working model, not a
crash — so a conservative table is hard-coded here as the fallback.

Selection order
---------------
1. No CUDA at all -> the CPU fallback strategy.
2. Exact match on this GPU's capability block.
3. Nearest measured neighbour: same (dtype, causal, padded), then closest
   sequence length in log space, then closest batch.
4. The table's overall default.
5. `"baseline"`, which is always registered and always correct.

Every step is filtered by three gates that can only remove candidates, never add
them. The strategy must be **registered** on this machine, **supported by this
GPU's capability**, and **numerically correct in the requested dtype**.

The third gate is the subtle one. A strategy can be perfectly implemented, fast,
and still unable to meet the tolerance in a given precision — bf16 against this
reference is the worked example (see `docs/INTERFACE.md` §5.1). Such a strategy
declares `SUPPORTED_DTYPES`, and dispatch will never hand it an input it cannot
compute correctly. Without this gate the hard-coded fallback would happily
select a fp32/fp16-only strategy for a bf16 tensor and return quietly wrong
numbers, which is the worst failure mode available: not a crash, not a slowdown,
but a plausible wrong answer.

Cost
----
`select_strategy` is memoised on its arguments, so the steady-state cost in a
forward pass is a dict lookup on a small tuple. Building the key is the only
part that touches the tensor; see `DispatchKey.from_forward` for the one
GPU-sync hazard there and how to avoid it.
"""

from __future__ import annotations

import functools
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Mapping, Optional, Sequence, Tuple

import torch

__all__ = [
    "DispatchKey", "Decision", "device_capability", "capability_name",
    "select_strategy", "explain", "load_table", "clear_caches",
    "CPU_FALLBACK_STRATEGY", "FALLBACK_TABLE",
]

DEFAULT_TABLE_PATH = "results/dispatch_table.json"

#: What to run when there is no GPU at all.
#:
#: `"baseline"` is the safe answer and the current one. Whether an SDPA path is
#: numerically safe on CPU is an open question for Person A
#: (docs/APPROVALS_NEEDED.md 1.2); until it is answered, a wrong answer here
#: would fail the correctness oracle on the only machine that runs it in CI.
CPU_FALLBACK_STRATEGY = "baseline"

#: Used when `results/dispatch_table.json` is absent. Deliberately tiny: it
#: encodes the *mechanism* rather than any measurement. Attention is the term
#: that grows as S^2, so a path that avoids materializing [B, H, S, S] should
#: win at long sequences; that is a prediction, not a result, and it is replaced
#: by measured data the moment a sweep has run. Everything in it still passes
#: through the registration and capability gates.
FALLBACK_TABLE: Dict[str, object] = {
    "default": "sdpa",
    "meta": {"source": "hard-coded fallback in src/dispatch.py — not measured"},
}

#: Minimum compute capability per strategy, when the strategy class does not
#: declare `MIN_CAPABILITY` itself. Name-based, because dispatch has to work
#: from the JSON table alone, before any class is imported.
#:
#: (8, 0) — bf16 arithmetic needs Ampere; on Turing it is emulated and slow.
#: (7, 5) — Triton and flash-style kernels need Turing or newer.
_NAME_CAPABILITY_RULES: Sequence[Tuple[str, Tuple[int, int]]] = (
    ("bf16", (8, 0)),
    ("bfloat16", (8, 0)),
    ("triton", (7, 5)),
    ("flash", (7, 5)),
)


@dataclass(frozen=True)
class DispatchKey:
    """Everything the dispatcher is allowed to see at call time.

    Note what is absent: `layers`. Depth changes how long a forward pass takes
    but not which kernel is right for a shape, and including it would fragment
    the table into keys that were never measured separately.
    """

    batch: int
    seq_len: int
    d_model: int
    heads: int
    dtype: str
    causal: bool
    padded: bool

    def table_key(self) -> str:
        """The exact string `analysis/load.py` writes as a JSON key."""
        return ",".join((
            str(self.batch), str(self.seq_len), str(self.d_model),
            str(self.heads), str(self.dtype), str(self.causal), str(self.padded),
        ))

    @classmethod
    def from_forward(
        cls,
        x: torch.Tensor,
        valid_token_mask: Optional[torch.Tensor],
        config,
        padded: Optional[bool] = None,
    ) -> "DispatchKey":
        """Build a key inside `forward`.

        `padded` is worth passing explicitly. Deriving it means asking whether
        the mask is all-True, and on CUDA that reduction has to be read back to
        the host — a synchronisation in the middle of a hot forward pass. It is
        cheap relative to a long-sequence forward and not cheap relative to a
        short one. In the benchmark harness padding is a property of the
        configuration and is known before the call, so pass it and skip the
        question entirely.
        """
        batch, seq_len, d_model = x.shape
        if padded is None:
            padded = bool(
                valid_token_mask is not None and not bool(valid_token_mask.all())
            )
        return cls(
            batch=int(batch), seq_len=int(seq_len), d_model=int(d_model),
            heads=int(config.num_heads), dtype=str(x.dtype).replace("torch.", ""),
            causal=bool(config.causal), padded=bool(padded),
        )


@dataclass(frozen=True)
class Decision:
    """A chosen strategy plus why, so a run can always explain itself."""

    strategy: str
    reason: str


def device_capability(device: Optional[torch.device] = None) -> Optional[Tuple[int, int]]:
    """(major, minor) for the current CUDA device, or None when there is no GPU."""
    if not torch.cuda.is_available():
        return None
    try:
        return tuple(torch.cuda.get_device_capability(device))  # type: ignore[return-value]
    except (RuntimeError, AssertionError):
        return None


def capability_name(capability: Tuple[int, int]) -> str:
    """(8, 9) -> 'sm_89'. The key `analysis/load.py` writes its block under."""
    return f"sm_{capability[0]}{capability[1]}"


@functools.lru_cache(maxsize=8)
def load_table(table_path: str = DEFAULT_TABLE_PATH) -> Mapping[str, object]:
    """Read the generated table, or fall back. Cached; never raises.

    A malformed or missing file degrades to `FALLBACK_TABLE` rather than
    propagating: this runs inside `forward`, and a model that refuses to run
    because a JSON file is unreadable is worse than one that runs a slower
    kernel.
    """
    path = Path(table_path)
    try:
        table = json.loads(path.read_text())
    except (OSError, ValueError):
        return FALLBACK_TABLE
    if not isinstance(table, dict):
        return FALLBACK_TABLE
    return table


def clear_caches() -> None:
    """Drop memoised tables and decisions. For tests, and after a re-sweep."""
    load_table.cache_clear()
    _select_cached.cache_clear()


# ---------------------------------------------------------------------------
# gates
# ---------------------------------------------------------------------------

def _supported_dtypes(name: str, cls: Optional[type]) -> Optional[frozenset]:
    """Dtypes this strategy claims to be correct in, or None for "all".

    Only a class can declare this. A name appearing in the JSON table with no
    class behind it on this machine is already excluded by the registration
    gate, so there is nothing to guess.
    """
    declared = getattr(cls, "SUPPORTED_DTYPES", None)
    if declared is None:
        return None
    return frozenset(str(d).replace("torch.", "") for d in declared)


def _minimum_capability(name: str, cls: Optional[type]) -> Optional[Tuple[int, int]]:
    """What this strategy needs. A class declaration beats the name heuristic.

    The heuristic exists because dispatch has to be able to reason about a name
    that appears only in the JSON table, with no class behind it on this
    machine. A class that declares `MIN_CAPABILITY` is always believed instead —
    a strategy knows its own requirements better than its name does.
    """
    declared = getattr(cls, "MIN_CAPABILITY", None)
    if declared is not None:
        return tuple(declared)  # type: ignore[return-value]
    lowered = name.lower()
    needed = [
        requirement for marker, requirement in _NAME_CAPABILITY_RULES
        if marker in lowered
    ]
    return max(needed) if needed else None


#: (name, minimum capability or None, supported dtypes or None) for everything
#: runnable here. Resolved before memoisation so the cache key carries the
#: requirements themselves rather than names that would have to be looked up
#: again — looking them up again in the global registry silently drops the
#: requirements of any strategy passed in explicitly, which is exactly the bug
#: this shape prevents.
Requirements = Tuple[Tuple[str, Optional[Tuple[int, int]], Optional[frozenset]], ...]


def _requirements(available: Mapping[str, type]) -> Requirements:
    return tuple(sorted(
        (name, _minimum_capability(name, cls), _supported_dtypes(name, cls))
        for name, cls in available.items()
    ))


def _is_allowed(
    name: str,
    capability: Tuple[int, int],
    requirements: Requirements,
    dtype: Optional[str] = None,
) -> bool:
    """Registered here, supported by this card, and correct in this dtype."""
    for candidate, required, dtypes in requirements:
        if candidate != name:
            continue
        if required is not None and capability < required:
            return False
        if dtype is not None and dtypes is not None and dtype not in dtypes:
            return False
        return True
    return False


def _registry() -> Dict[str, type]:
    from src.strategies import STRATEGIES

    return dict(STRATEGIES)


# ---------------------------------------------------------------------------
# nearest neighbour
# ---------------------------------------------------------------------------

def _parse_key(raw: str) -> Optional[DispatchKey]:
    parts = raw.split(",")
    if len(parts) != 7:
        return None
    try:
        return DispatchKey(
            batch=int(parts[0]), seq_len=int(parts[1]), d_model=int(parts[2]),
            heads=int(parts[3]), dtype=parts[4],
            causal=parts[5].strip().lower() == "true",
            padded=parts[6].strip().lower() == "true",
        )
    except ValueError:
        return None


def _nearest(key: DispatchKey, entries: Mapping[str, str]) -> Optional[Tuple[str, str]]:
    """Closest measured key sharing (dtype, causal, padded).

    Distance is log-scaled on sequence length and batch, because these axes are
    swept multiplicatively: S=1024 is far closer to S=2048 than the linear gap
    to S=128 suggests, and a linear metric would pick the wrong neighbour every
    time.

    Only keys with the *same* mask and dtype behaviour are considered. Borrowing
    a measurement across a causal/padded boundary would mean recommending a
    kernel for a branch it was never measured on.
    """
    candidates = []
    for raw, strategy in entries.items():
        parsed = _parse_key(raw)
        if parsed is None:
            continue
        if (parsed.dtype, parsed.causal, parsed.padded) != (key.dtype, key.causal, key.padded):
            continue
        distance = (
            abs(math.log2(max(parsed.seq_len, 1) / max(key.seq_len, 1))),
            abs(math.log2(max(parsed.batch, 1) / max(key.batch, 1))),
            abs(math.log2(max(parsed.d_model, 1) / max(key.d_model, 1))),
        )
        candidates.append((distance, raw, strategy))
    if not candidates:
        return None
    _, raw, strategy = min(candidates, key=lambda item: item[0])
    return raw, strategy


# ---------------------------------------------------------------------------
# selection
# ---------------------------------------------------------------------------

_AUTO = object()


def _decide(
    key: DispatchKey,
    capability: Optional[Tuple[int, int]],
    table_path: str,
    requirements: Requirements,
) -> Decision:
    if capability is None:
        return Decision(
            CPU_FALLBACK_STRATEGY,
            f"no CUDA device -> {CPU_FALLBACK_STRATEGY}",
        )

    table = load_table(table_path)
    block_name = capability_name(capability)
    raw_block = table.get(block_name)
    measured_here = isinstance(raw_block, dict) and bool(raw_block)
    entries = raw_block if isinstance(raw_block, dict) else {}

    def gated(name: Optional[str]) -> bool:
        return bool(name) and _is_allowed(
            str(name), capability, requirements, key.dtype
        )

    # 3. exact match
    exact = entries.get(key.table_key())
    if gated(exact):
        return Decision(str(exact), f"exact match {block_name} {key.table_key()} -> {exact}")
    rejected = f" (measured {exact!r} rejected: {_why_rejected(str(exact), capability, requirements, key.dtype)})" if exact else ""

    # 4. nearest measured neighbour
    neighbour = _nearest(key, {k: v for k, v in entries.items() if gated(v)})
    if neighbour is not None:
        raw, strategy = neighbour
        return Decision(
            strategy,
            f"nearest measured neighbour {block_name} {raw} -> {strategy}{rejected}",
        )

    # 5. the table's default
    default = table.get("default")
    if gated(default):
        # Distinguish "we measured this card but not this shape" from "we have
        # never measured this card at all". The report has to be able to say
        # which, because only the first is a performance claim.
        if table is FALLBACK_TABLE:
            why = "no measured data at all; hard-coded fallback default"
        elif measured_here:
            why = f"no {block_name} key for {key.table_key()}; table default"
        else:
            why = f"no measured data for {block_name}; table default"
        return Decision(str(default), f"{why} -> {default}{rejected}")

    # 6. the control, which is always registered and always correct
    return Decision(
        "baseline",
        f"nothing applicable for {block_name} {key.table_key()} -> baseline{rejected}",
    )


def _why_rejected(
    name: str, capability: Tuple[int, int], requirements: Requirements, dtype: str
) -> str:
    """Which gate removed this candidate. "Rejected" alone is not actionable."""
    for candidate, required, dtypes in requirements:
        if candidate != name:
            continue
        if required is not None and capability < required:
            return f"needs sm_{required[0]}{required[1]}+, this card is {capability_name(capability)}"
        if dtypes is not None and dtype not in dtypes:
            return f"does not support {dtype} (declares {sorted(dtypes)})"
        return "allowed"
    return "not registered on this machine"


@functools.lru_cache(maxsize=512)
def _select_cached(
    key: DispatchKey,
    capability: Optional[Tuple[int, int]],
    table_path: str,
    requirements: Requirements,
) -> Decision:
    return _decide(key, capability, table_path, requirements)


def _decide_for(
    key: DispatchKey,
    capability,
    table_path: str,
    available: Optional[Mapping[str, type]],
) -> Decision:
    if capability is _AUTO:
        capability = device_capability()
    if available is None:
        available = _registry()
    return _select_cached(key, capability, table_path, _requirements(available))


def select_strategy(
    key: DispatchKey,
    capability=_AUTO,
    table_path: str = DEFAULT_TABLE_PATH,
    available: Optional[Mapping[str, type]] = None,
) -> str:
    """The strategy name to use for `key`.

    `capability` defaults to auto-detection. Pass an explicit `(major, minor)`
    to force a decision for another card — that is how the sm_75 and sm_80 paths
    are correctness-tested without owning those cards — or an explicit `None` to
    force the no-GPU path.

    `available` defaults to the live strategy registry; pass a mapping to test
    selection independently of what happens to be registered.

    **This function is depth-blind.** `DispatchKey` carries no layer count, and
    numerical admissibility can depend on one: fp16 passes at a single layer and
    fails from two, once error has compounded through the residual stream. A
    strategy declaring `SUPPORTED_DTYPES = (float32, float16)` is telling the
    truth, and this function will still offer it an fp16 tensor at six layers
    where it fails. Any such depth rule belongs in the entry point that knows
    the config -- `src/optimized.py` -- not here. See TECH_REPORT §7.2.
    """
    return _decide_for(key, capability, table_path, available).strategy


def explain(
    key: DispatchKey,
    capability=_AUTO,
    table_path: str = DEFAULT_TABLE_PATH,
    available: Optional[Mapping[str, type]] = None,
) -> str:
    """One line saying which strategy was chosen and why.

    Worth logging at least once per process: a speedup nobody can attribute to a
    specific code path is not a result anyone can act on.
    """
    return _decide_for(key, capability, table_path, available).reason
