"""Regenerate every derived artefact from results.csv and logs/.

    python -m analysis.make_all

This is the single command the README's "reproduce" section points at, and the
only thing that writes into `results/figures/`, `results/dispatch_table.json`
and `results/summary.md`. Nothing here reads a hand-maintained file: if a number
appears in the report, it came through here from an append-only log, and
re-running reproduces it.

It is deliberately tolerant of a half-finished sweep. A figure with no data
renders as a labelled empty panel saying which sweep would fill it, rather than
raising — so the pipeline can be run and inspected from day one, and a missing
figure is never mistaken for a broken one.
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional, Sequence

from analysis import figures
from analysis.load import (
    crossover_table, dispatch_choices, latest_per_config, load_results,
    results_markdown_table, speedup_summary, status_counts, usable,
)
from analysis.roofline import RTX_4050_LAPTOP, plot_roofline, ridge_point

DEFAULT_RESULTS = "results/results.csv"
DEFAULT_LOGS = "logs"
DEFAULT_FIGURES = "results/figures"
DEFAULT_SUMMARY = "results/summary.md"
DEFAULT_DISPATCH = "results/dispatch_table.json"


def _write_summary(frame, path: Path, figure_paths: Sequence[Path],
                   source: Path = Path(DEFAULT_RESULTS)) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    counts = status_counts(frame)
    summaries = speedup_summary(frame)
    measured = usable(frame)

    synthetic = "fixtures" in str(source) or "synthetic" in source.name
    lines: List[str] = ["# Results summary", ""]
    if synthetic:
        # Nothing here was measured. Say so before any number is read, because a
        # plausible-looking table is exactly what gets quoted by mistake.
        lines += [
            "> ## ⚠ SYNTHETIC DATA — NOT MEASUREMENTS",
            "> ",
            f"> Generated from `{source}`, a fixture of invented numbers used to "
            "develop and test the analysis layer before any GPU run existed. "
            "Every figure and every number below is fake. Do not quote any of it.",
            "",
        ]
    lines += [
        f"_Generated by `python -m analysis.make_all`. Do not edit by hand — "
        f"every number here is derived from `{source}`._",
        "",
        f"Generated: {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        "",
        "## Row counts by status",
        "",
        "| status | rows | meaning |",
        "|---|---|---|",
    ]
    meanings = {
        "PASS": "a usable measurement",
        "FAIL": "implementation was wrong; timing withheld",
        "SKIPPED": "memory pre-check refused the config",
        "OOM_BASELINE": "baseline could not run; optimized did",
        "DISCARDED": "clock fell >15% mid-run; excluded from summaries",
    }
    for status in ("PASS", "FAIL", "SKIPPED", "OOM_BASELINE", "DISCARDED"):
        lines.append(f"| {status} | {counts.get(status, 0)} | {meanings[status]} |")

    lines += [
        "",
        f"Distinct configurations measured: "
        f"{latest_per_config(frame)['config_key'].nunique() if not measured.empty else 0}",
        "",
        "## Speedup by strategy",
        "",
        "Geometric mean, because speedups are ratios: a strategy that is 2x on "
        "one shape and 0.5x on another has done nothing on average, and only the "
        "geometric mean says so.",
        "",
        "| strategy | geomean | min | max | n |",
        "|---|---|---|---|---|",
    ]
    if summaries:
        for item in summaries:
            lines.append(
                f"| {item.strategy} | **{item.geomean:.3f}x** | {item.minimum:.3f}x "
                f"| {item.maximum:.3f}x | {item.n} |"
            )
    else:
        lines.append("| _no passing rows yet_ | — | — | — | 0 |")

    control = next((s for s in summaries if s.strategy == "baseline"), None)
    if control is not None:
        verdict = "PASS" if 0.97 <= control.geomean <= 1.03 else "**FAILED**"
        lines += [
            "",
            f"Control check: `baseline` measures {control.geomean:.3f}x — {verdict}. "
            "The control is a copy of the reference model, so anything outside "
            "0.97–1.03x means the measuring rig is wrong and no other row here "
            "can be trusted.",
        ]

    lines += ["", "## Speedup by sequence length", "", results_markdown_table(frame)]

    choices = dispatch_choices(frame)
    if not choices.empty:
        clear = choices[choices["margin"].notna() & (choices["margin"] >= 0.05)]
        lines += [
            "",
            "## Dispatch",
            "",
            f"{len(choices)} dispatch keys; "
            f"{choices['best_strategy'].nunique()} distinct winners "
            f"({', '.join(sorted(choices['best_strategy'].unique()))}).",
            "",
            f"{len(clear)} of {len(choices)} keys are won by a margin of 0.05x or "
            "more. Keys won by less than that are ties in practice — the choice "
            "there is within run-to-run noise and should not be read as a result.",
            "",
            "| dispatch key (B,S,d,H,dtype,causal,padded) | best | speedup | runner-up | margin |",
            "|---|---|---|---|---|",
        ]
        for _, row in choices.sort_values("best_speedup", ascending=False).iterrows():
            margin = "—" if row["margin"] is None else f"{row['margin']:.3f}"
            runner = row["runner_up"] or "—"
            lines.append(
                f"| `{row['dispatch_key']}` | {row['best_strategy']} | "
                f"{row['best_speedup']:.3f}x | {runner} | {margin} |"
            )

    lines += [
        "",
        "## Roofline reference",
        "",
        f"Machine: {RTX_4050_LAPTOP.name} — "
        f"{RTX_4050_LAPTOP.peak_fp32_tflops:g} TFLOP/s fp32, "
        f"{RTX_4050_LAPTOP.peak_bf16_tflops:g} TFLOP/s bf16, "
        f"{RTX_4050_LAPTOP.bandwidth_gbs:g} GB/s.",
        "",
        f"- fp32 ridge point: **{ridge_point(RTX_4050_LAPTOP.peak_fp32_tflops, RTX_4050_LAPTOP.bandwidth_gbs):.1f} FLOP/byte**",
        f"- bf16 ridge point: **{ridge_point(RTX_4050_LAPTOP.peak_bf16_tflops, RTX_4050_LAPTOP.bandwidth_gbs):.1f} FLOP/byte**",
        "",
        "_Peak figures are placeholders until Person A confirms them from the "
        "spec sheet (docs/APPROVALS_NEEDED.md §1.4). Every ridge point scales "
        "directly with them._",
        "",
        "## Figures",
        "",
    ]
    for figure_path in figure_paths:
        lines.append(f"- `{figure_path}`")

    path.write_text("\n".join(lines) + "\n")
    return path


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m analysis.make_all")
    parser.add_argument("--results", default=DEFAULT_RESULTS)
    parser.add_argument("--logs", default=DEFAULT_LOGS)
    parser.add_argument("--figures", default=DEFAULT_FIGURES)
    parser.add_argument("--summary", default=DEFAULT_SUMMARY)
    parser.add_argument("--dispatch", default=DEFAULT_DISPATCH)
    parser.add_argument("--capability", default="sm_89",
                        help="GPU the measurements came from; keys the dispatch table")
    args = parser.parse_args(argv)

    results_path = Path(args.results)
    if not results_path.exists():
        print(
            f"no results at {results_path}. Run a sweep first:\n"
            f"  python bench/sweep.py --strategy baseline --matrix quick",
            file=sys.stderr,
        )
        return 1

    frame = load_results(results_path)
    print(f"loaded {len(frame)} rows from {results_path}: {status_counts(frame)}")

    figure_dir = Path(args.figures)
    produced: List[Path] = []
    for function in figures.ALL_FIGURES:
        produced.append(function(frame, out_dir=figure_dir))
        print(f"  {produced[-1]}")

    produced.append(plot_roofline(frame, out_dir=figure_dir))
    print(f"  {produced[-1]}")

    # One thermal figure per clock log. There may be none (no GPU, no sweep yet).
    clock_logs = sorted(Path(args.logs).glob("clocks_*.csv"))
    for log in clock_logs:
        produced.append(
            figures.thermal_trace(log, out_dir=figure_dir,
                                  filename=f"thermal_{log.stem}.png")
        )
        print(f"  {produced[-1]}")
    if not clock_logs:
        print(f"  (no clock logs in {args.logs}/ — thermal figures skipped)")

    from analysis.load import write_dispatch_table

    dispatch_path = write_dispatch_table(frame, args.dispatch, capability=args.capability)
    print(f"  {dispatch_path}")

    summary_path = _write_summary(frame, Path(args.summary), produced, results_path)
    print(f"  {summary_path}")

    crossover = crossover_table(frame)
    if not crossover.empty:
        print(
            f"\n{len(crossover)} configs; best overall: "
            f"{speedup_summary(frame)[0].strategy} "
            f"({speedup_summary(frame)[0].geomean:.3f}x geomean)"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
